import Head from 'next/head'
import { Sidebar } from '../components/Sidebar'
import Container from '@mui/material/Container'

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Whatsapp Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <Sidebar />
        </div>
      </main>
    </>
  )
}

export default Home
